### ISSUE TITLE
How to create Field with OneToMany

### ISSUE THREAD

**Issue by korolariya** [prismake/typegql#10]
I try 
```
 @OneToMany(type => Family, family => family.childhood)
    @Field({type: () => Family})
    family: Family[];
```

> Error: @ObjectType Family.childhood: Validation of type failed. Resolved type for @Field must be GraphQLOutputType.

**Comment by pie6k** [comment]
Can you paste  definition of Family class?

**Comment by korolariya** [comment]
`import {Entity} from 'typeorm/decorator/entity/Entity';
import {BaseEntity, ManyToOne, PrimaryGeneratedColumn} from 'typeorm';
import {Profile} from './Profile';
import {FamilyRank} from './FamilyRank';
import {Childhood} from './Childhood';
import {FamilyStatus} from './FamilyStatus';
import {FamilyTragedy} from './FamilyTragedy';
import {Parents} from './Parents';
import {Field, ObjectType} from 'typegql';

@Entity()
@ObjectType()
export class Family extends BaseEntity{
    @PrimaryGeneratedColumn()
    @Field()
    id: number;

    @ManyToOne(type => Profile, profile => profile.family)
    @Field()
    profile: Profile;

    @ManyToOne(type => FamilyRank, familyRank => familyRank.family)
    @Field()
    familyRank: FamilyRank;

    @ManyToOne(type => Childhood, childhood => childhood.family)
    @Field()
    childhood: Childhood;

    @ManyToOne(type => FamilyStatus, familyStatus => familyStatus.family)
    @Field()
    familyStatus: FamilyStatus;

    @ManyToOne(type => FamilyTragedy, familyTragedy => familyTragedy.family)
    @Field()
    familyTragedy: FamilyTragedy;

    @ManyToOne(type => Parents, parents => parents.family)
    @Field()
    parents: Parents;
}
`

`import {BaseEntity, Column, OneToMany, PrimaryGeneratedColumn} from 'typeorm';
import {Entity} from 'typeorm/decorator/entity/Entity';
import {Family} from './Family';
import {Field, ObjectType} from 'typegql';

/**
 * Childhood environment
 */
@Entity()
@ObjectType()
export class Childhood extends BaseEntity {
    @PrimaryGeneratedColumn()
    @Field()
    id: number;

    @Column()
    @Field()
    name: string;

    @OneToMany(type => Family, family => family.childhood)
    @Field()
    family: Family[];
}
`

**Comment by pie6k** [comment]
I see few potential issues:

1. Seems you have circular relationship (Childhood > Family > Childhood > Family) etc. In such case, you have to define type as function. (http://siawyoung.com/coding/javascript/circular-references-graphql-type-definitions.html)

We'd have to modify 

```ts
    @ManyToOne(type => Childhood, childhood => childhood.family)
    @Field()
    childhood: Childhood;
```

to 

```ts
    @ManyToOne(type => Childhood, childhood => childhood.family)
    @Field({ type: () => Childhood })
    childhood: Childhood;
```

Also change 

```ts
    @OneToMany(type => Family, family => family.childhood)
    @Field()
    family: Family[];
```

to

```ts
    @OneToMany(type => Family, family => family.childhood)
    @Field({ type: () => [Family] })
    family: Family[];
```


And let me know if that helps.

Note that if you use array types (eg. `Family[]`) you'd have to set type manually anyway as typescript is not able to guess type of array item.

**Comment by korolariya** [comment]
it works but not quite.
My query 
```
{
  getFamilies{
    id
    childhood {
      id
      name
    } 
  }
}
```
Family:
```
@Entity()
@ObjectType()
export class Family extends BaseEntity {
    @PrimaryGeneratedColumn()
    @Field()
    id: number;

    @ManyToOne(type => Childhood, childhood => childhood.family)
    @Field({type: () => Childhood})
    childhood(): Childhood {
        return Childhood.findOneById(1);
    };
...
}
```
Childhood:
```
@Entity()
@ObjectType()
export class Childhood extends BaseEntity {
    @PrimaryGeneratedColumn()
    @Field()
    id: number;

    @Column()
    @Field()
    name: string;

    @OneToMany(type => Family, family => family.childhood)
    @Field({type: () => [Family]})
    family: Family[];
}

```

Response:
```
{
  "data": {
    "getFamilies": [
      {
        "id": 1,
        "childhood": {
          "id": 1,
          "name": "Spent on the Street, with no adult supervision"
        }
      }
    ]
  }
}
```
I do not understand how to get here ID 

> @ManyToOne(type => Childhood, childhood => childhood.family)
>     @Field({type: () => Childhood})
>     childhood(): Childhood {
>         return Childhood.findOneById(1);
>     };

**Comment by 19majkel94** [comment]
@korolariya 
> But sometimes you want to know what is the "profile id" of this user without loading the whole profile for this user. To do this you just need to add another property to your entity with @Column named exactly as the column created by your relation.
http://typeorm.io/#/relations-faq/how-to-use-relation-id-without-joining-relation

You can take a look at this in my simple TypeORM example:
https://github.com/19majkel94/type-graphql/blob/master/examples/typeorm-basic-usage/resolvers/rate-resolver.ts#L16

However the easier approach is to use lazy relations and let TypeORM fetch this automatically:
https://github.com/19majkel94/type-graphql/blob/master/examples/typeorm-lazy-relations/entities/rate.ts

**Comment by pie6k** [comment]
@korolariya you dont have to define function that returns your `Childhood`s. Typeorm is handling it by itself.

So basically you could simply

```ts
@ManyToOne(type => Childhood, childhood => childhood.family)
@Field({type: () => Childhood})
childhood: Childhood;
```

**Comment by 19majkel94** [comment]
> Typeorm is handling it by itself.
@pie6k Only with lazy relations. Normally you need to overfetch them in main query or fetch manually in field resolver. Try that by yourself by creating more advanced TypeORM example than [the basic one](https://github.com/prismake/typegql/tree/master/examples/typeorm-basic-integration).

**Comment by korolariya** [comment]
It awesome, thanks. Everything works, I will continue to study.
