### ISSUE TITLE
Are graphql list types supported?

### ISSUE THREAD

**Issue by fahrradflucht** [prismake/typegql#17]
I found no way to make arrays / graphql lists work. Aren't they supported or did I just not get it?

**Comment by fahrradflucht** [comment]
ah searched an hour, opened an issue and then immediately found it out. On just needs to set the type explicitly to a tuple of the list element type like so:
`@Query({ type: [Product] })`;

**Comment by pie6k** [comment]
Right. I'll try to make it clearer in docs as indeed, there is no clear note about this.

**Comment by fahrradflucht** [comment]
What I noticed is that this is kind of a predetermined breaking point isn't it? I mean neither at ts compile time nor at compileSchema time something is validating that the type I forced there matches my returned type...

**Comment by pie6k** [comment]
Not sure if I understand. You mean - if there is any validation that would check if what your resolver returns is what you've told it will return?

If so - it will happen when schema is resolving real queries. But indeed there is no way to validate it earlier.
