### ISSUE TITLE
Field decorator does not support getters

### ISSUE THREAD

**Issue by capaj** [prismake/typegql#26]
I've been using typegql with objection.js for a little while now and I have couple of getters in my codebase. Would it be possible to support them? Currently typegql is throwing when I try to put `@Field` on a getter.

**Comment by pie6k** [comment]
Could you paste some example code that is throwing?

**Comment by pie6k** [comment]
That's interesting. Could you explain why do you need getter here? Also, when exactly are you getting this error?

Seems it's expecting something to be nullable. Could you try to set field config to `@Field({ isNullable: true })`.

But still, it should return `10` propably. I'll take a look!

**Comment by pie6k** [comment]
Ok I think I've found something. It's treating it as function and trying to find arguments list, while it's getter. I'll hopefully fix it today.

**Comment by pie6k** [comment]
I've added support for getter based fields together with needed test: https://github.com/prismake/typegql/commit/85d017e98d0c8d216e70dcff484b05d4acfb301f

Try to update to `0.5.2` and let me know if it's working now.

**Comment by capaj** [comment]
@pie6k awesome :tada: so fast :tornado: As soon as NPM let's me install that version I'll try it out. Been having issues whole day.
