### ISSUE TITLE
getters are invoked with a wrong context and also they are invoked on startup when inferring native types

### ISSUE THREAD

**Issue by capaj** [prismake/typegql#32]
function `inferTypeByTarget` just accesses a variable in order to infer a type. This is not compatible with getters, because it is invoking them just by accesing it.

Also when getters are invoked at runtime they are invoked on the prototype rather than from `source`. This causes problems when getters try to access some instance field. Fix incoming.

**Comment by capaj** [comment]
@pie6k same as with the other one- I can open it as soon as you merge prettier branch.

**Comment by pie6k** [comment]
Great! I've merged PR with prettier now :)

**Comment by pie6k** [comment]
It's fixed. I've added proper test cases. Also thanks for your PR @capaj !
