### ISSUE TITLE
Feature request: an alias for @Field({isNullable: false})

### ISSUE THREAD

**Issue by capaj** [prismake/typegql#34]
this is written often and is quite verbose to write. Compared to just `@Field()` it's much lengthier.
If there was an alias such as `@FieldNN` or maybe `@NonNullField` it would definitely save me some reading/writing.

From the implementation perspective it's trivial and I think the saved characters are worth having such alias.

**Comment by pie6k** [comment]
Right. Implementation is trivial: 

```ts
interface NonNullFieldOptions extends FieldOptions {
  isNullable: never;
}

export function NonNullField(options?: NonNullFieldOptions) {
  return Field({...options, isNullable: false});
}
```

But I'm kinda opposing to that. I believe having more configurations is always making project harder to maintain.

What do you think about making fields `NonNull` by default?

**Comment by pie6k** [comment]
I was thinking a bit about this and I've decided to not do this.

It'll require the same thing for input fields aka `NonNullInputField` and propably the same for interface fields soon. Could be the same with other ideas that might come soon.

Also, `NonNullField` is still a field. 

Perhaps we can return to this topic when there will be more supporting it voices or other reasons for it. For now I'll close it.

Also as an aliast - it's very easy to create it yourself in your project.
