### ISSUE TITLE
Example of having resolvers in separate files

### ISSUE THREAD

**Issue by jdolle** [prismake/typegql#52]
In my experience, resolvers can get pretty large. Because of this, I am afraid defining all resolvers in the schema class will become unwieldy. What is the best approach to moving a resolver to a separate file, then using it in the schema class?

If there is an agreement on such a process, I would be happy to amend the documentation.
Currently I have found one approach that seems promising:

```
import doSomething from "..."

@Mutation()
  public doSomething(
    @Inject(doSomething) value: boolean,
  ): boolean {
    return value
  }
```

**Comment by ryanzjohnson** [comment]
I would also like to know this as well. We want to define our schemas in one package that also our consumers use. Then define the resolvers in our private server code. If that's at all possible.

**Comment by capaj** [comment]
I don't know if I am not missing something, but you certainly can have a `SchemaClass` which exposes your internal class.
So:
```js
const myUberPrivateSchema = {
  a() {...}
}

// somewhere else
@SchemaRoot()
export class Schema { 
  @Mutation()
  public a() {
    return myUberPrivateSchema.a()
  }
}
```

**Comment by pie6k** [comment]
Exactly for reason you've described, single schema can have multiple schema roots.

Example:

```ts
import { SchemaRoot, Query, Mutation, compileSchema } from "typegql";

@SchemaRoot()
export class UserSchemaRoot {
  @Query()
  allUsers() {}
}

@SchemaRoot()
export class UserMutationsSchemaRoot {
  @Mutation()
  registerUser() {}
}

@SchemaRoot()
export class ProductSchemaRoot {
  @Query()
  allProducts() {}
}

const finalSchema = compileSchema([UserSchemaRoot, UserMutationsSchemaRoot, ProductSchemaRoot])
```

As seen, final schema is composed from many 'root' classes. Obviously, those classes can be defined in different files and imported.

**Comment by jdolle** [comment]
Works for my purposes. Thanks
