### ISSUE TITLE
feature request: @MutationField and @QueryField

### ISSUE THREAD

**Issue by capaj** [prismake/typegql#54]
Currently if I return a class from `@Mutation()` and `@Query()` and I want to have a field like `patch`(
![image](https://user-images.githubusercontent.com/1305378/42689053-16f9d6ea-869f-11e8-8102-0d04e64b4a7f.png)
) on the class, this field is exposed on mutations and on queries as well. I'd like to avoid this-hence the new decorator. This could be achieved with a decorator config like `@Field({mutationOnly: true})` or `@Field({query: false})`, but IMHO it's own decorator is more explicit way.

**Comment by pie6k** [comment]
I didnt understand your question. I'd appreciate if you take your time re-writing it :)

**Comment by capaj** [comment]
basically:

```js
@ObjectType()
class User {
  @Field() name: string

  @Field() price: number

  @Field() // here I would use the MutationField
  setSuperUser(): User {
    return this
  }
}

@Schema()
class SuperSchema {
  @Mutation()
  createUser(name: string, price: number): User {
    const user = new User()
    return user
  }

  @Query()
  @Mutation()
  getUserById(id: number): User {
    return new User()
  }
}

const schema = compileSchema({ roots: [SuperSchema2] })
console.log('schema: ', printSchema(schema))
```

now the compiled schema looks like:
```
type Mutation {
  createUser(name: String!, price: Float!): User
 getUserById(id: Float!): User
}

type Query {
  getUserById(id: Float!): User
}

type User {
  name: String
  price: Float
  setSuperUser: User
}
```

Now anyone can just call this query:
```
{
 getUserById(1) { setSuperUser {name}}
}
```
but I would like them to only be able to call that via a mutation like

```
mutation {
 getUserById(1) { setSuperUser {name}}
}

currently they can call it like a query and mutation both.
```

**Comment by pie6k** [comment]
First of all, I think `getUserById` should be inside query, not inside mutation. Mutations are meant to mutate the state of the app.

Anyway, I see you're using 

```ts
  @Query()
  @Mutation()
  getUserById(id: number): User {
    return new User()
  }
```

You're using both `Mutation` and `Query` decorator - that's the reason it's bresent in both. If you'd leave only `@Mutation` - it'll not be present in `query` anymore.

**Comment by capaj** [comment]
The thing is I have a `User` class. This class has `Field`s which are reading so they are gql queries, but it also has `Field` which are mutating the `User` instance.
That  is why I have both `Query` and `Mutation` decorators there.
If I only put `Query` there, I can't call
```
mutation {
 getUserById(1) { setSuperUser {name}}
}
```

**Comment by pie6k** [comment]
Having field that is mutating is rather not good idea.

**Comment by pie6k** [comment]
Could you describe in details your desired schema?
