### ISSUE TITLE
Can I somehow pass context directly to resolver?

### ISSUE THREAD

**Issue by Blitss** [prismake/typegql#64]
As well as I know, I can only get the context in `@Before` decorator. How can I do something like this?

```
@Query({ type: [Provider] })
  async providers({ context }): Promise<Provider[]> {
```

It might be useful to specify things that belong to the authenticated user (in the database query, where clause) or get user itself, like `me{}`.

**Comment by pie6k** [comment]
Sure, checkout @Context argument decorator:

https://prismake.github.io/typegql/explore/inject/

If you need more fine control, use raw @Inject decorator, also described in link above.
