### ISSUE TITLE
Arguments To Query Type Not Exposed/Compiled?

### ISSUE THREAD

**Issue by elmpp** [prismake/typegql#68]
Hi there, think the library fits a real good niche. The typeorm fit in particular is real nice

I've hit a wall however when trying to accepts arguments to a query field. The schema just doesn't seem to include the `name` argument for the query field.

I have experimented at length with adding `@Arg()` etc also

Here's a reproduction repo - https://github.com/elmpp/typegql-params

This screenshot shows the graphiql request failing - https://github.com/elmpp/typegql-params/blob/master/ScreenShot.png

**Comment by pie6k** [comment]
https://prismake.github.io/typegql/getting-started/setup.html

Make sure to add `"emitDecoratorMetadata": true,` to your `tsconfig`.

Let me know if it helps

**Comment by elmpp** [comment]
That's done it. Cheers very much
